version: "3.0"

services:
  frontapp:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    image: frontapp:latest
    ports:
      - "8080:80"

  backapp:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    image: backapp:latest
    ports:
      - "8081.80"
